name: Build React Native Android APK

on:
  push:
    branches:
      - main  # Runs when you push to the 'main' branch
  pull_request:
    branches:
      - main  # Runs on pull requests to 'main'
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest  # Runs on Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pulls your project from GitHub

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Adjust based on your project's requirements
          cache: 'npm'

      - name: Install dependencies
        run: npm install  # Installs React Native dependencies

      - name: Setup Java for Android
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3  # Sets up Android SDK

      - name: Grant execution permission to Gradle
        run: chmod +x android/gradlew  # Ensures Gradle is executable

      - name: Build APK
        run: cd android && ./gradlew assembleRelease  # Builds APK

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
